#!/bin/sh

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

#### meta start
#### project Whonix
#### category networking and firewall
#### description ifupdown pre-up.d hook to load Whonix Firewall
#### meta end

set -e

/usr/bin/whonix_firewall
